### ISSUE TITLE
Abstain from renaming branches

### ISSUE THREAD

**Issue by ftrippel** [thollander/actions-comment-pull-request#24]
First: Thank you for all the work you put into this.

One more thing: Please abstain from renaming branches in the future. The github syntax forced us to name a branch when using your github action. So we hardwired "master", and now we have to go through 30 projects to rename it to "main". Actually I would suggest to just stick with conventions or at least not change directions.

**Comment by lazyoracle** [comment]
Yep. Came here for this. So many projects are broken 😢

But again: Thank you for building this and putting all the effort into it.

**Comment by thollander** [comment]
Sorry about it, didn't know it had some impact on workflows, I would have put it into a breaking change if so. 
You may need to fix the version of the action to a specific one to avoid this.

**Comment by ericcornelissen** [comment]
It may be a little late but you (@thollander) could add a new branch or tag called `master` to provide backwards compatibility to users that hardwired `master` into their workflow files. You could either keep it up-to-date forever (in the case of a tag by just `--force` pushing a newer tag; in the case of a branch by just keeping it pointing to the same commit as `main`). Alternatively, you could make `master` a branch with a slightly altered version of the action that always outputs a warning that the user should change to `main` (or a specific version) - possibly before a specific date so that you can at least remote that `master` branch at some point.

Additionally, following the [official versioning guidelines](https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#versioning), I would suggest you switch from recommending the usage of the default branch of your repository to a continuously updated `v1` tag, which should always point to the latest `v1.x.x` version available. This has several advantages, including avoiding problems such as the one described in this issue.

**Comment by thollander** [comment]
Yes, I gues it's a bit too late to manage it as you suggested (main = master) but that was a good idea. 

Totally agree with you, I'll create an issue to manage versionning in a proper way, thanks for taking time for this feedback.
